const c=document.querySelector('#game'),x=c.getContext('2d'),$=s=>document.querySelector(s),T=48,W=80,H=12,G=1600;
const keys={left:false,right:false,jump:false};let map,hero,enemies,coins,cam,score,lives=3,running=false,paused=false,last=0,audio;
const raw=[
"                                                                                ",
"                                                                                ",
"                                                                                ",
"                C                    C C                         C               ",
"          BBB        BBBB       BBB        BBB       BBBBB                       ",
"                              C                                BBB              ",
"                        P                    P            C                       ",
"       C       E                         E       E                    E      F  ",
"  S           ####         #####             ######       ####            #######",
"######   ###########   ############   ##############   ###########   ###########",
"######   ###########   ############   ##############   ###########   ###########",
"######   ###########   ############   ##############   ###########   ###########"];
function reset(){map=raw.map(r=>r.padEnd(W).split(''));enemies=[];coins=[];let start={x:96,y:300};map.forEach((r,y)=>r.forEach((v,q)=>{if(v==='S'){start={x:q*T,y:y*T};map[y][q]=' '}if(v==='E'){enemies.push({x:q*T,y:y*T-36,w:38,h:36,vx:-85,vy:0,alive:true});map[y][q]=' '}if(v==='C'){coins.push({x:q*T+12,y:6*T+10,taken:false});map[y][q]=' '}}));hero={x:start.x,y:start.y-44,w:34,h:44,vx:0,vy:0,ground:false,dead:false};cam=0;score=0;running=true;paused=false;last=performance.now();hide();ui();requestAnimationFrame(loop)}
function solid(tx,ty){if(tx<0||tx>=W||ty<0||ty>=H)return false;return'#BP'.includes(map[ty][tx])}
function physics(o,dt){o.vy+=G*dt;o.x+=o.vx*dt;collide(o,'x');o.y+=o.vy*dt;o.ground=false;collide(o,'y')}
function collide(o,axis){const l=Math.floor(o.x/T),r=Math.floor((o.x+o.w-1)/T),t=Math.floor(o.y/T),b=Math.floor((o.y+o.h-1)/T);for(let q=l;q<=r;q++)for(let y=t;y<=b;y++)if(solid(q,y)){if(axis==='x'){if(o.vx>0)o.x=q*T-o.w;else if(o.vx<0)o.x=(q+1)*T;o.vx=0}else{if(o.vy>0){o.y=y*T-o.h;o.ground=true}else if(o.vy<0)o.y=(y+1)*T;o.vy=0}}}
function update(dt){hero.vx=(keys.right-keys.left)*260;if(keys.jump&&hero.ground){hero.vy=-610;hero.ground=false;tone(420,.06)}physics(hero,dt);if(hero.y>650)return die();coins.forEach(o=>{if(!o.taken&&hit(hero,{x:o.x,y:o.y,w:24,h:24})){o.taken=true;score+=100;tone(760,.06)}});enemies.forEach(e=>{if(!e.alive)return;const old=e.vx;physics(e,dt);if(e.vx===0)e.vx=-old;if(hit(hero,e)){if(hero.vy>120&&hero.y+hero.h-e.y<25){e.alive=false;hero.vy=-330;score+=200;tone(190,.08)}else die()}});const flagX=raw[7].indexOf('F')*T;if(hero.x>flagX){score+=1000;running=false;show('COURSE CLEAR','過關！',`漂亮！本關得到 ${score} 分。`,'再玩一次')}cam=Math.max(0,Math.min(hero.x-300,W*T-960));ui()}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function die(){if(hero.dead)return;hero.dead=true;lives--;tone(90,.3);if(lives<=0){running=false;show('GAME OVER','冒險結束','別灰心，像素勇者會再次站起來。','重新挑戰')}else setTimeout(()=>{hero.x=96;hero.y=300;hero.vx=hero.vy=0;hero.dead=false;cam=0},650);ui()}
function tile(q,y,v){const px=q*T-cam,py=y*T;if(v==='#'){x.fillStyle='#9b6033';x.fillRect(px,py,T,T);x.fillStyle='#d6964c';x.fillRect(px,py,T,8);x.strokeStyle='#6b3d27';x.strokeRect(px+.5,py+.5,T-1,T-1)}if(v==='B'){x.fillStyle='#e2793e';x.fillRect(px+2,py+2,T-4,T-4);x.fillStyle='#ffc05b';x.fillRect(px+6,py+6,T-12,5);x.strokeStyle='#743625';x.strokeRect(px+2,py+2,T-4,T-4)}if(v==='P'){x.fillStyle='#49a654';x.fillRect(px+5,py,T-10,T);x.fillStyle='#82e66f';x.fillRect(px,py,T,10)}}
function draw(){x.fillStyle='#63c9f1';x.fillRect(0,0,960,540);x.fillStyle='#fff';for(let i=0;i<8;i++){let px=(i*190-cam*.18)%1200;if(px<0)px+=1200;x.fillRect(px,78+(i%3)*50,70,18);x.fillRect(px+18,66+(i%3)*50,35,18)}x.fillStyle='#55b96a';for(let i=0;i<12;i++){const px=i*150-cam*.45;x.beginPath();x.arc(px,470,90,Math.PI,0);x.fill()}map.forEach((r,y)=>r.forEach((v,q)=>v!==' '&&v!=='F'&&tile(q,y,v)));coins.forEach((o,i)=>{if(o.taken)return;x.fillStyle='#ffd43b';x.beginPath();x.ellipse(o.x+12-cam,o.y+12,7+Math.sin(performance.now()/150+i)*3,12,0,0,7);x.fill()});enemies.forEach(e=>{if(!e.alive)return;const px=e.x-cam;x.fillStyle='#623b35';x.fillRect(px,e.y+10,e.w,e.h-10);x.fillStyle='#fff';x.fillRect(px+7,e.y+14,7,8);x.fillRect(px+24,e.y+14,7,8);x.fillStyle='#111';x.fillRect(px+10,e.y+17,3,5);x.fillRect(px+24,e.y+17,3,5)});const fx=raw[7].indexOf('F')*T-cam;x.fillStyle='#eee';x.fillRect(fx,110,6,330);x.fillStyle='#ef4b3f';x.fillRect(fx+6,118,76,45);x.fillStyle='#ffd447';x.fillRect(fx+17,130,17,17);if(!hero.dead){const px=hero.x-cam;x.fillStyle='#f04c43';x.fillRect(px+4,hero.y,26,12);x.fillStyle='#ffd39b';x.fillRect(px+7,hero.y+12,22,14);x.fillStyle='#244f88';x.fillRect(px+3,hero.y+26,28,18);x.fillStyle='#fff';x.fillRect(px+21,hero.y+14,4,5)}}
function loop(t){if(!running)return;const dt=Math.min((t-last)/1000,.03);last=t;if(!paused)update(dt);draw();requestAnimationFrame(loop)}
function ui(){$('#score').textContent=String(score).padStart(6,'0');$('#coins').textContent=String(coins?.filter(o=>o.taken).length||0).padStart(2,'0');$('#lives').textContent='♥'.repeat(Math.max(lives,0))}
function show(k,t,m,b){$('#kicker').textContent=k;$('#title').textContent=t;$('#message').innerHTML=m;$('#start').textContent=b;$('#overlay').classList.remove('hidden')}function hide(){$('#overlay').classList.add('hidden')}
function tone(f,d){audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function press(k,v){if(k==='jump'&&v&&running&&!paused&&hero.ground){hero.vy=-610;hero.ground=false}keys[k]=v}document.addEventListener('keydown',e=>{const m={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'jump',w:'jump',' ':'jump'},k=m[e.key.toLowerCase()];if(k){e.preventDefault();press(k,true)}if(e.key.toLowerCase()==='p'&&running){paused=!paused;paused?show('PAUSED','遊戲暫停','按 P 繼續冒險。','繼續'):hide()}});document.addEventListener('keyup',e=>{const m={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'jump',w:'jump',' ':'jump'},k=m[e.key.toLowerCase()];if(k)press(k,false)});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();press(b.dataset.key,true)};b.onpointerup=b.onpointercancel=()=>press(b.dataset.key,false)});$('#start').onclick=()=>paused?(paused=false,hide()):(lives=3,reset());map=raw.map(r=>r.padEnd(W).split(''));hero={x:96,y:300,w:34,h:44};enemies=[];coins=[];cam=score=0;draw();ui();
