const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s),GRID=20,CELL=28;
let players=[],food,mode='solo',running=false,paused=false,last=0,stepMs=150,soundOn=true,audio,touchStart;
const high=()=>Number(localStorage.getItem('nightSnakeHigh')||0),same=(a,b)=>a.x===b.x&&a.y===b.y;
function makePlayer(id,snake,dir,color){return{id,snake,dir:{...dir},nextDir:{...dir},score:0,color}}
function reset(){players=[makePlayer(1,[{x:5,y:10},{x:4,y:10},{x:3,y:10}],{x:1,y:0},'green')];if(mode==='duo')players.push(makePlayer(2,[{x:14,y:10},{x:15,y:10},{x:16,y:10}],{x:-1,y:0},'blue'));food=spawnFood();stepMs=150;running=true;paused=false;last=performance.now();updateUI();hideOverlay();draw();requestAnimationFrame(loop)}
function spawnFood(){let p;do{p={x:Math.floor(Math.random()*GRID),y:Math.floor(Math.random()*GRID)}}while(players.some(a=>a.snake.some(s=>same(s,p))));return p}
function setDirection(id,x,y){const p=players.find(a=>a.id===id);if(!running||paused||!p||(x===-p.dir.x&&y===-p.dir.y))return;p.nextDir={x,y}}
function tick(){const moves=players.map(p=>{p.dir=p.nextDir;const head={x:p.snake[0].x+p.dir.x,y:p.snake[0].y+p.dir.y},eating=head.x===food.x&&head.y===food.y;return{p,head,eating}});moves.forEach(m=>{const own=m.eating?m.p.snake:m.p.snake.slice(0,-1),others=players.filter(p=>p!==m.p).flatMap(p=>p.snake);m.dead=m.head.x<0||m.head.x>=GRID||m.head.y<0||m.head.y>=GRID||own.some(s=>same(s,m.head))||others.some(s=>same(s,m.head))});if(moves.length===2&&same(moves[0].head,moves[1].head))moves.forEach(m=>m.dead=true);if(moves.some(m=>m.dead))return gameOver(moves);let ate=false;moves.forEach(m=>{m.p.snake.unshift(m.head);if(m.eating){m.p.score+=10;ate=true}else m.p.snake.pop()});if(ate){food=spawnFood();const longest=Math.max(...players.map(p=>p.snake.length));stepMs=Math.max(65,150-Math.floor((longest-3)/3)*8);beep(620,.06)}updateUI()}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function draw(){ctx.fillStyle='#07130e';ctx.fillRect(0,0,560,560);ctx.strokeStyle='#10251b';for(let i=1;i<GRID;i++){ctx.beginPath();ctx.moveTo(i*CELL,0);ctx.lineTo(i*CELL,560);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*CELL);ctx.lineTo(560,i*CELL);ctx.stroke()}ctx.save();ctx.shadowColor='#d7ff70';ctx.shadowBlur=18;ctx.fillStyle='#d7ff70';ctx.beginPath();ctx.arc(food.x*CELL+14,food.y*CELL+14,8,0,Math.PI*2);ctx.fill();ctx.restore();players.forEach(p=>p.snake.forEach((s,i)=>{const gap=i?3:2,x=s.x*CELL+gap,y=s.y*CELL+gap,size=CELL-gap*2;if(p.color==='blue')ctx.fillStyle=i===0?'#6ee7ff':`hsl(${190+i*.35} 70% ${Math.max(37,58-i*.6)}%)`;else ctx.fillStyle=i===0?'#baff67':`hsl(${148-i*.55} 67% ${Math.max(36,58-i*.65)}%)`;roundedRect(x,y,size,size,i?7:9);ctx.fill();if(!i){ctx.fillStyle='#092015';const eyes=p.dir.x!==0?[{x:.68,y:.27},{x:.68,y:.68}]:[{x:.27,y:.3},{x:.68,y:.3}];eyes.forEach(e=>{ctx.beginPath();ctx.arc(x+size*e.x,y+size*e.y,2.7,0,Math.PI*2);ctx.fill()})}}))}
function loop(t){if(!running)return;if(!paused&&t-last>=stepMs){tick();last=t;draw()}requestAnimationFrame(loop)}
function updateUI(){const p1=players[0],p2=players[1];$('#scoreLabel').textContent=mode==='duo'?'玩家 1 分數':'目前分數';$('#score2Label').textContent=mode==='duo'?'玩家 2 分數':'最高分';$('#lengthLabel').textContent=mode==='duo'?'最長蛇身':'蛇身長度';$('#score').textContent=p1?.score||0;$('#score2').textContent=mode==='duo'?(p2?.score||0):Math.max(p1?.score||0,high());$('#length').textContent=Math.max(...players.map(p=>p.snake.length));$('#speed').textContent=(150/stepMs).toFixed(1).replace('.0','')+'×'}
function showOverlay(kicker,title,text,button,showModes=false){$('#overlayKicker').textContent=kicker;$('#overlayTitle').textContent=title;$('#overlayText').innerHTML=text;$('#startBtn').textContent=button;$('#modeChoice').style.display=showModes?'flex':'none';$('#overlay').classList.remove('hidden')}
function hideOverlay(){$('#overlay').classList.add('hidden')}
function gameOver(moves){running=false;const total=players.reduce((n,p)=>n+p.score,0);if(mode==='solo')localStorage.setItem('nightSnakeHigh',Math.max(total,high()));let result=`得到 <b>${total}</b> 分。`;if(mode==='duo'){const dead=moves.filter(m=>m.dead);result=dead.length===2?'兩位玩家平手！':`<b>玩家 ${dead[0].p.id===1?2:1}</b> 獲勝！`;}updateUI();showOverlay('旅程結束','撞到了！',result,'再玩一次',true);beep(95,.3)}
function togglePause(){if(!running)return;paused=!paused;if(paused)showOverlay('稍作休息','遊戲暫停','按下繼續，回到夜色中。','繼續');else{last=performance.now();hideOverlay()}}
function beep(freq,duration){if(!soundOn)return;audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
document.addEventListener('keydown',e=>{const key=e.key.toLowerCase(),p1={w:'up',s:'down',a:'left',d:'right'},p2={arrowup:'up',arrowdown:'down',arrowleft:'left',arrowright:'right'};if(p1[key]){e.preventDefault();setDirection(1,...dirs[p1[key]])}if(p2[key]){e.preventDefault();setDirection(mode==='duo'?2:1,...dirs[p2[key]])}if(e.code==='Space'){e.preventDefault();togglePause()}});
document.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();setDirection(1,...dirs[b.dataset.dir])}));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));updateUI()});
canvas.addEventListener('pointerdown',e=>touchStart={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;if(Math.max(Math.abs(dx),Math.abs(dy))>20)setDirection(1,...dirs[Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up')]);touchStart=null});
$('#startBtn').onclick=()=>paused?togglePause():reset();$('#pauseBtn').onclick=togglePause;$('#soundBtn').onclick=()=>{soundOn=!soundOn;$('#soundBtn').textContent=`音效：${soundOn?'開':'關'}`};
players=[makePlayer(1,[{x:10,y:10},{x:9,y:10},{x:8,y:10}],{x:1,y:0},'green')];food={x:14,y:10};updateUI();draw();
